{% set name = "gi-docgen" %}
{% set version = "2024.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2a4a5569f91109777481aa71451751289227f7c2652cfac366184a41eb19c231

build:
  entry_points:
    - gi-docgen=gidocgen.gidocmain:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - jinja2
    - markdown
    - markupsafe
    - packaging
    - pygments
    - python >={{ python_min }}
    - toml
    - typogrify

test:
  imports:
    - gidocgen
  commands:
    - pip check
    - gi-docgen --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.gnome.org/GNOME/gi-docgen
  summary: Documentation tool for GObject-based libraries
  license: GPL-3.0-or-later
  license_file: LICENSES/

extra:
  recipe-maintainers:
    - pkgw
