{% set name = "gi-docgen" %}
{% set version = "2023.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gi-docgen-{{ version }}.tar.gz
  sha256: 88adeda9cbf882569479701eada009afa5d94fa29d728653ec388c32035f7fa3

build:
  entry_points:
    - gi-docgen=gidocgen.gidocmain:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - jinja2
    - markdown
    - markupsafe
    - pygments
    - python >=3.6
    - toml
    - typogrify

test:
  imports:
    - gidocgen
  commands:
    - pip check
    - gi-docgen --help
  requires:
    - pip

about:
  home: https://gitlab.gnome.org/GNOME/gi-docgen
  summary: Documentation tool for GObject-based libraries
  license: GPL-3.0-or-later
  license_file: LICENSES/

extra:
  recipe-maintainers:
    - pkgw
